### PR TITLE
Tiny yolo v3 classifier inference code

### PR DESCRIPTION
**Pull request by Karthikeya108**
We are create the tiny yolo model and loading the weights saved from the training. We fetch the anchor points and classes from the files in the config directory (`tl_detector/config`) and the model weights from `tl_detector/models` directory.

The model weights (yolo-tiny.h5 file) will be checked in from a different branch.

Most of the code snippets (model.py and utils.py) has be taken from the tiny yolo v3 keras implementation:
https://github.com/qqwweee/keras-yolo3

---
All traffic light classifier were moved to separate files. It will simplify code navigation. 

New module structure:
```
light_classification/
    __init__.py  
    tl_classifier.py
    ssd_tl_classifier.py
    opencv_tl_classifier.py
    yolo/
        yolo_tl_classifier.py
        model.py  # file from another repo
        utils.py  # file from another repo
```

### CODE REVIEW

**Comment by thejerrytan** [comment]
a lot of things going on here.

**Comment by ser94mor** [comment]
This pull request **introduces 2 alerts** when merging d6959cb53e758c0b3a47500c707a1f139439e34f into f6ce1e747b343168cce24e36fb472757c838af4e - [view on LGTM.com](https://lgtm.com/projects/g/aoool/self-driving-car-using-ros/rev/pr-b582a9609b26407ec4286635e67d4711b1b7e203)

**new alerts:**

* 1 for Except block handles &#39;BaseException&#39;
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by pkorivi — APPROVED** [review]

**Comment by ser94mor** [comment]
This pull request **introduces 1 alert** when merging 83a5c617a7992256f4810c5ba2d16facbb2b3d9b into fd5b6170c568c9198bf83d94dc7106a71d735eec - [view on LGTM.com](https://lgtm.com/projects/g/aoool/self-driving-car-using-ros/rev/pr-570f025b58da2f08b1853f18d9a2fc3d993606dc)

**new alerts:**

* 1 for Nested loops with same variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ser94mor** [comment]
This pull request **introduces 1 alert** when merging c000bbec5dac547ad74dbbd17304aad6b796da4c into fd5b6170c568c9198bf83d94dc7106a71d735eec - [view on LGTM.com](https://lgtm.com/projects/g/aoool/self-driving-car-using-ros/rev/pr-58dbba430e9ed5b9ab828a32f128fff131839b24)

**new alerts:**

* 1 for Nested loops with same variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by ser94mor — APPROVED** [review]

**Comment by ser94mor** [comment]
This pull request **introduces 84 alerts** when merging 82e18ac7684c932c93a8aac49daeb6ec2907721f into fd5b6170c568c9198bf83d94dc7106a71d735eec - [view on LGTM.com](https://lgtm.com/projects/g/aoool/self-driving-car-using-ros/rev/pr-ad105f32d270b58ff4f0238359f3830e4393db08)

**new alerts:**

* 39 for Unused import
* 18 for &#39;import \*&#39; may pollute namespace
* 6 for Variable defined multiple times
* 4 for Missing call to \_\_init\_\_ during object initialization
* 3 for Comparison using is when operands support \_\_eq\_\_
* 3 for Suspicious unused loop iteration variable
* 3 for First argument to super\(\) is not enclosing class
* 2 for Unused local variable
* 2 for Mismatch between signature and use of an overridden method
* 2 for Redundant assignment
* 1 for Except block handles &#39;BaseException&#39;
* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
